version: '3'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
      POSTGRES_USER: root
    ports: 
      - 5433:5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
